lubi(marta, wino).
lubi(marta, mandarynki).
lubi(marta, tenis).
lubi(marta, kwiaty).
lubi(piotr, banany).
lubi(piotr, wino).
lubi(piotr, tenis).
lubi(jan, banany).
lubi(jan, wino).
lubi(jan, tenis).
lubi(ania, wino).
lubi(ania, tenis).